### ISSUE TITLE
[ToDo] Upgrade Photon package to it's latest version

### ISSUE THREAD

**Issue by OpenHogwarts** [OpenHogwarts/hogwarts#12]
Upgrade Photon package to it's latest version.

**Comment by kardall** [comment]
Question, @OpenHogwarts do you have the ability to view the Photon Database directly? Can you modify it directly?

Reason: Adding UI Elements (things that do not change), Localization.
I want to have set ID's for UI Elements, that would be retrieved via the database.
So for example:

ID = 1
Description = Main Menu Level Text
Values = { "Nivel", "Level" }

Usage of said UI Function:

public Text Level;
public Text Connect;
public Text CreateCharacter;
public Text ConnectTest;

```
public string GetUIText(int uiElementId) {
	return Service.getOne<UIText>("FROM interface WHERE locale == ? & character == ? & uid == ?", (int)Locales.ConvertPlayerLocale(), PhotonNetwork.player.customProperties["characterId"], uiElementId);
}
```

Something like that. So if there was a way that we could make an SQL or even a dev script that will empty the interface table, and rebuild it with different versions of the game, that way the element ID's can be updated/changed with each release.

**Comment by OpenHogwarts** [comment]
Photon doesn't have any db, it's de multiplayer layer. The db that we use is iBoxDB (http://www.iboxdb.com/) it's offline/in localhost for each player. There is no shared db across the users :o

**Comment by kardall** [comment]
Ok so future outlook then.

If you were to have this as an "MMO" where you wanted more than one person to have your quests (you as the dungeon master), and they participate with you.

You need to either
1) Have a package setup of that session that is loaded in the game somehow either on-load or in-game UI.
2) You have a main server with some kind of storage for 'sessions' or Story Arcs. Each story arc would be accessible and loaded when the player logs in or select the arc from an in-game UI.

Some mix of the two?

Having a local only DB makes no sense for more than one person :)

**Comment by OpenHogwarts** [comment]
Well, it's a way to have multiplayer serverless builds -> Master Client. A client that also acts as server Let me explain:
A way to make multiplayer quests without a shared db is:
- All players have the [quests list in local](https://github.com/OpenHogwarts/hogwarts/blob/master/Assets/Scripts/Quest/QuestManager.cs#L110) (each quest has an id, and all stuff)
- Once a player starts a quest/raid/whatever, he shares with the other connected players the quest id/raid id, etc..  Master client will validate that request and if accepted, will give orders to other clients.

Right now, this is how NPCs are begin controlled & act synced for everyone. Once you get near to an NPC position, system checks if its "mind" is begin processed by a player. If not, it will assign that NPC to you so it starts moving while keeps synced for eveyone.

I don't know if i'm making it harder to understand or more cleaner xD

**Comment by kardall** [comment]
Understand.
It would be a massive undertaking to do a solo database setup for a single person's usage for say, "Hogwarts of Europe" chapters.

Would be completely awesome.

Have packages (pre-compiled scenarios) that the organizer would supply download links to, as well as the database that supports their scenario.

anyway... so many ideas haha

**Comment by kardall** [comment]
On a side note, put a pull request in. I did some of those changes, and removed my Locale so that I can put it in a separate branch :D

**Comment by OpenHogwarts** [comment]
Yep! Checked it, just misses 2 changes and i will merge it :P

**Comment by finchen** [comment]
done in https://github.com/OpenHogwarts/hogwarts/pull/69
