### ISSUE TITLE
Stair climbing not possible

### ISSUE THREAD

**Issue by Sh4d0w08** [OpenHogwarts/hogwarts#15]
The character can´t climb stairs. If you jump the character just glitches around.

**Comment by Sh4d0w08** [comment]
Also I wanted to ask for contact details like an E-mail adress, because i want to help you with the project.

**Comment by OpenHogwarts** [comment]
:o ¿In which tasks would you like to participate?

**Comment by Sh4d0w08** [comment]
I just have basic knowledge in #C, so i thought about redoing the terrain because it isnt that beautiful...

**Comment by OpenHogwarts** [comment]
¡That would be so cool!

**Comment by kardall** [comment]
Just made a pull request to kind of fix some of them. It is going to take some time. But I think I got all the stairs leading up the Interior Gran Comedor towards Griff's dorms. Not sure but ... It will take a while to do it. Have to make a plane, rotate/scale/move the plane over top of the stair edges to make a ramp. Then remove the Mesh Renderer so it isn't rendering 'a plane'. It just becomes a Collider at that point, which the character can totally walk on. :)

**Comment by OpenHogwarts** [comment]
¡Thank you for fixing this too!

It's really curious to see someone streaming how he fixes the game xD

**Comment by kardall** [comment]
heh, ya once all the planes are in place, you could probably group them all together, when you don't have to move them anymore. Makes it easier to sort until the models are updated if possible.

I can try to hammer through a few, but that room is ungodly big ;s And I don't know where there are other stairs yet so haha

**Comment by OpenHogwarts** [comment]
I don't think they will get updated so the best approach to fix it is the one you made. Placing a rotated plane collider on the stairs. Nobody sees it, but lets everyone "climb" the stairs :)

**Comment by kardall** [comment]
Streaming fixing them right now: http://www.twitch.tv/kardall :)

**Comment by OpenHogwarts** [comment]
Saw you having a "great" combat experience xD
