### ISSUE TITLE
Harry spawns more than once when logged out in between

### ISSUE THREAD

**Issue by jongleur1983** [OpenHogwarts/hogwarts#17]
I started the game, walked around and logged out (not quitting the game entirely).
Re-entered, now Harry spawns twice at the usual starting location.
Logging out and enter again: Harry exists three times, and so on.

**Comment by jongleur1983** [comment]
seems not to be restricted to Harry, but the Head-up display as well.

**Comment by OpenHogwarts** [comment]
Disconnect option disabled (https://github.com/OpenHogwarts/hogwarts/commit/a58063c9255a4877c7675089941f23218f04820c )

(It's not finished so shouldn't be available in ESC panel)
