### ISSUE TITLE
Help understanding structure

### ISSUE THREAD

**Issue by Granheart** [OpenHogwarts/hogwarts#18]
Hello!

I've been trying to figure the system out. 
Where do the game save each characters data? Can't find it. How can it remember my character?

And how can you tell the system which level to load? 

For example when you click the test button:
public void joinTest () {
        Menu.defaultLevel = Menu.debugLevel;
        joinGame (playerId, "Tester"); 

But how does it know which scene is the "debugLevel"?
If I would like to add maybe a new scene to a button, how could I do it?

Someone please explain! :) Thank you!

**Comment by OpenHogwarts** [comment]
We have a small wiki here: https://github.com/OpenHogwarts/hogwarts/wiki

Game's data (like character) is saved in iBoxDB, a db system where you can make sql like queries :)

He knows what level is here:
https://github.com/OpenHogwarts/hogwarts/blob/master/Assets/Scripts/UI/Menu.cs#L13

To add a  new scene to a button, you should:
- Add the new scene to Unity -> Build settings
- Create a function (lets think you want to add it on the main panel) in MainPanel.cs to load it and then call that function in the UI Button (MainMenu scene -> Canvas -> MainPanel -> YourButton name)

**Comment by Granheart** [comment]
Thank you for the fast answer! I knew it was some kind of DB becuase of the scripts, yet I've never found the actual files. Like for my character. I recognise that "Granheart" character is lv2 and it is created, so I can log in, but If I want to look at that character's data, can I find it somewhere? ><

The database structure is still new to me. Sorry for bothering you with this.

**Comment by OpenHogwarts** [comment]
There is not db browser client, the only what to look at the data is by making a query and printing the result :o

If you check https://github.com/OpenHogwarts/hogwarts/wiki/Access-game-DB you will see how to make queries and also what does character table contain (https://github.com/OpenHogwarts/hogwarts/blob/master/Assets/Scripts/Player/CharacterData.cs)
