### ISSUE TITLE
I would like to contribute but...?

### ISSUE THREAD

**Issue by noxerr** [OpenHogwarts/hogwarts#19]
Hello, I got here searching harry potter assets to develope something similar. Do you use any method of comunication between you apart from github?

danielrl1994@gmail.com, contact me I would like to contribute.

**Comment by OpenHogwarts** [comment]
Sorry for not replying before.
We also talk here: http://www.forocoches.com/foro/showthread.php?t=4898418 :)

**Comment by noxerr** [comment]
I have no account there, send me an email and talk via whatsapp? Im from spain too btw

**Comment by AlexCSilva** [comment]
I'd join the forum but don't know alot of spanish haha

**Comment by OpenHogwarts** [comment]
@AlexCSilva there's no need to signup, if you want to contribute, the list of pending tasks is here :P
https://github.com/OpenHogwarts/hogwarts/wiki/ToDo

**Comment by AlexCSilva** [comment]
Sweet, I know java which is apparently similar to C#, i also plan to write some fanfics for the books :P and be cool to have text books with actual content lol got all these ideas. Im a fan of the rpg games on gameboy as well :)

**Comment by AlexCSilva** [comment]
I checked out the game today, pretty nice work done so far. Btw i'm half portuguese so i understand tiny bit of spanish. buen trabajo amigos!
i like how u use mouse to turn pages on books

**Comment by kenokaicer** [comment]
Hellow! Estoy intentando corregir algunas issues pero tengo problemas en comprender ciertos aspectos, como la DB y el PhotonPun. Si puedes contactarte conmigo seria genial. aralo@live.com.ar

**Comment by OpenHogwarts** [comment]
Photon Engine (network framework) documentation can be found here:
https://doc.photonengine.com/en-us/pun/current/getting-started/pun-intro

DB info is available in Wiki:
https://github.com/OpenHogwarts/hogwarts/wiki

And for DB syntax you can check:
http://www.iboxdb.com/
