### ISSUE TITLE
Open in UNity

### ISSUE THREAD

**Issue by seanamor** [OpenHogwarts/hogwarts#2]
Can you perhaps explain more thoroughly how I clone the repo and open it in Unity, I have recently downloaded Unity but cant understand how to open it to "play" the map.

**Comment by danimoreno3d** [comment]
Hi there, I do not know how to play that do not touch me, I'm not very
professional unity


2016-02-23 19:41 GMT+01:00 seanamor <notifications@github.com>:

**Comment by seanamor** [comment]
Its alright I figured it out. Thanks

**Comment by OpenHogwarts** [comment]
We're sorry to not have replied you until now. As our lack of programmers the project got frozen :(

We will improve the setup instructions in the readme file.
¿Do you think those are better?
- Clone/Download this repo (https://github.com/OpenHogwarts/hogwarts/archive/master.zip)
- Open the downloaded folder in Unity (File -> Open Project)
- In Unity project's folders double click MainMenu (Assets -> Scenes -> MainMenu)
- Hit the start button from Game tab. Inside the game, click create a New Character, set the name and click on "Entrar".
