### ISSUE TITLE
Initial menu has overlapped buttons

### ISSUE THREAD

**Issue by craigmayhew** [OpenHogwarts/hogwarts#20]
The first menu with "crear personaie" appears to have another button, but they are overlapped. I've tried several different resolutions and the effect is the same.

If I click the top button in the layer, I am taken to a screen to fill in a username, but it doesn't let me get any further.

The instructions say that "Entrar" should appear, but it doesn't.

Please let me know how I can help debug this, happy to provide log output, screenshots etc.

**Comment by Vancete** [comment]
Can you record a little video?

Please, try running the game as admin and check if it continues happening
(maybe the db file is not being created properly).

2017-01-23 12:09 GMT+01:00 Craig Mayhew <notifications@github.com>:

**Comment by craigmayhew** [comment]
Images were easier than video for me. You can see that step 7 looks the same as step 1 and that step 8 looks similar to step 2 as it looks like it should progress but fails to.

![step5](https://cloud.githubusercontent.com/assets/1750203/22204298/302509c8-e169-11e6-8744-e5b4e91c3f65.PNG)
![step6](https://cloud.githubusercontent.com/assets/1750203/22204303/3026bca0-e169-11e6-9058-edb47154206e.PNG)
![step7](https://cloud.githubusercontent.com/assets/1750203/22204301/30263eba-e169-11e6-92e6-b071f87fd72b.PNG)
![step8](https://cloud.githubusercontent.com/assets/1750203/22204300/30261ad4-e169-11e6-8272-c73028eac5b8.PNG)
![step1](https://cloud.githubusercontent.com/assets/1750203/22204299/30261c6e-e169-11e6-9c3c-d8ac07ed7f30.PNG)
![step2](https://cloud.githubusercontent.com/assets/1750203/22204302/30269ebe-e169-11e6-8d76-cc0122e94722.PNG)
![step3](https://cloud.githubusercontent.com/assets/1750203/22204304/30453b4e-e169-11e6-86fd-3360cbd10645.PNG)
![step4](https://cloud.githubusercontent.com/assets/1750203/22204305/3046812a-e169-11e6-9910-4ace0e3ee842.PNG)

**Comment by craigmayhew** [comment]
Also admin privileges didn't appear to make any difference, and in both cases I can see the db3.box file being created.

**Comment by OpenHogwarts** [comment]
Try running the game inside unity, maybe it throws an exception when clicking in "Crear Personaje" : o

**Comment by craigmayhew** [comment]
![console-output](https://cloud.githubusercontent.com/assets/1750203/22254189/cfb5573a-e24b-11e6-81f1-17cc7f7aa04f.PNG)

This is the set or errors I get when clocking that.

**Comment by OpenHogwarts** [comment]
I've never seen that error before.
¿O.S?

**Comment by craigmayhew** [comment]
Windows 10.  If no one else has experienced the issue, perhaps it's specific to this machine - I'll try to find out what I can.

**Comment by OpenHogwarts** [comment]
Mmmm, we all use win10 to code it, so nope, it's a code issue.
Try commenting this line:
https://github.com/OpenHogwarts/hogwarts/blob/master/Assets/Scripts/UI/Panels/MainPanel.cs#L22
As far as i know, it's the only one that makes an http request

**Comment by craigmayhew** [comment]
That has corrected the problem. The menu now loads two buttons, rather than having them overlapped and it allows me to enter the game!

Is there any other debug you would like me to try to get to the root cause? If not I'm happy that it now works for me.

**Comment by OpenHogwarts** [comment]
Well, github doesn't like to be used as CDN. We make a request to a json file hosted here, that tells to game the latest version available (a.k.a use github as CDN xD). So after multiple requests, he just starts denying them. 
We should disable that version check.
