### ISSUE TITLE
I keep crashing

### ISSUE THREAD

**Issue by CXFlameWheel** [OpenHogwarts/hogwarts#25]
When I try to play the game, the game always crashes. I have only tried a few times, but still, all the times I have clicked the file(even on something else) it has crashed

**Comment by OpenHogwarts** [comment]
It's quite hard to trace the problem with this amount of info, ¿Could you please anwser this questions?
- ¿Do you run a compiled version or inside Unity's editor?
- If compiled, ¿did you compile it?
- O.S
- Could you publish the error log? (https://docs.unity3d.com/Manual/LogFiles.html)
