### ISSUE TITLE
Still people working on this project ?

### ISSUE THREAD

**Issue by coupa10** [OpenHogwarts/hogwarts#36]
Title.

**Comment by OpenHogwarts** [comment]
I guess it is:
![https://i.imgur.com/8sCC3oa.png](https://i.imgur.com/8sCC3oa.png)

Check the readme: https://github.com/OpenHogwarts/hogwarts#why-development-is-so-slow

**Comment by coupa10** [comment]
I want to work on this project so hard, is there a Discord available ?
