### ISSUE TITLE
How to update language [English]

### ISSUE THREAD

**Issue by zercomnexus** [OpenHogwarts/hogwarts#39]
So i see the resource, however the binary download you have available is in spanish only with no option to switch to english that i can see. the instructions deal with programs and seem to assume that we know exactly what you are talking about, where it is, and where the files we need are already located. 

Please update this with a REAL step by step for the english , which english file to use (updated or the regular .json), where it goes, how to edit the necessary files for those that don't have unity editing experience, and please please please be precise and include all the steps.... otherwise you're going to have trouble bringing in support from anyone that speaks english if you can't even make directions easy/available/understandable.

**Comment by OpenHogwarts** [comment]
Binary download isn't in spanish only. Language is automatically selected based on your system language and English will be set as fallback if your language is not yet available:
https://github.com/OpenHogwarts/hogwarts/blob/master/Assets/Plugins/LanguageManager.cs#L32

A select could be added on settings panel for manual switching.

I'm not interested in bringing support, i'm already bringing the entire project code.
Setup instructions are for developing, if you're not planning to help on this project by coding/modding/etc.. ,which already requires having Unity experience, you don't need to follow them.
