### ISSUE TITLE
Can't open project - unity crashes?

### ISSUE THREAD

**Issue by ayseenver** [OpenHogwarts/hogwarts#45]
So I've downloaded the zip, unzipped it and opened the project in unity. However it has 999+ compiler errors and every time I try to open a scene unity crashes. Have I missed something?

**Comment by OpenHogwarts** [comment]
Can you post an screenshot of the error? :S

**Comment by ayseenver** [comment]
![image](https://user-images.githubusercontent.com/33575225/38164063-55454088-34f6-11e8-9404-a14f72d7fabf.png)

![ex1](https://user-images.githubusercontent.com/33575225/38164069-61c1e8de-34f6-11e8-8599-45283ddb2e10.PNG)

Here are some examples of the errors I get. If I double click on any scene unity just crashes to desktop. I'm using the latest version (Unity 2017.3.1), which is probably causing the issue :\

**Comment by ayseenver** [comment]
Right so after closing the project and opening it again I actually just get 1 error, this one:

![image](https://user-images.githubusercontent.com/33575225/38164384-9fc7f8a8-34fb-11e8-8c65-5eec4888b1cb.png)

**Comment by OpenHogwarts** [comment]
Which Unity version are you using? I don't see that error. (Don't use Unity's beta versions)

**Comment by ayseenver** [comment]
I'm using 2017.3.1. When I go into the LanguageManager.cs and try to type ScreenCapture, it won't fill the rest out for me and I get a red line underneath. Is it supposed to be defined/imported somewhere above? It looks like line 169 is the only reference to ScreenCapture in the whole file.

**Comment by ayseenver** [comment]
I double clicked on the MainMenu scene and it didn't crash to desktop. However the items are not showing up in the inspector, it's just a bunch of blank lines like this:

![image](https://user-images.githubusercontent.com/33575225/38164558-6e0c95d2-34fe-11e8-9c9b-ff6ddc4dcaa0.png)

My 999+ compiler errors are back, and i think its because all the objects do not exist for some reason.

![image](https://user-images.githubusercontent.com/33575225/38164567-850b0304-34fe-11e8-94de-aebe1f351c2a.png)

**Comment by OpenHogwarts** [comment]
That's quite strange, `ScreenCapture` (https://docs.unity3d.com/ScriptReference/ScreenCapture.html) is in `UnityEngine` namespace, which is begin declared on top of `LanguageManager.cs` (`using UnityEngine;`)
I've opened the project in Unity 2017.4.0f1 and isn't showin any error :S 
About the other errors, did you click play on Hogwarts scene? you should be clicking play on MainMenu one, that's the one that has `Canvas` object which will be moved to Hogwarts scene automatically when you play.

**Comment by ayseenver** [comment]
It works now, I reinstalled unity and downloaded the project again :)
