### ISSUE TITLE
How to change what NPCs say?

### ISSUE THREAD

**Issue by ayseenver** [OpenHogwarts/hogwarts#46]
I've placed a few more NPCs around the place by just duplicating existing talker NPCs. Is there a way for me to choose what I want each NPC to say? I see that each thing they say depends on what their ID is, but I can't seem to find where the phrases they say are being stored for me to edit/add to them.

**Comment by OpenHogwarts** [comment]
Mmm yes, that should be centralized on `DBSetup` maybe:
For quests:
https://github.com/OpenHogwarts/hogwarts/blob/7a2803c672e5fc55eb8e5947922ae88169deb2cf/Assets/Scripts/Quest/QuestManager.cs#L114

For talkers:
https://github.com/OpenHogwarts/hogwarts/blob/8275dc322def3fe8c963f7d280342905cbe6d17b/Assets/Scripts/UI/Panels/TalkPanel.cs#L12

**Comment by OpenHogwarts** [comment]
Done, this methods are now in `DBSetup` too and Wiki page got update too:
https://github.com/OpenHogwarts/hogwarts/wiki/Add-a-new-NPC

**Comment by ayseenver** [comment]
Thanks!
