### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by b3u** [OpenHogwarts/hogwarts#53]
_Such a cool idea!_ 🎈🎈 🎉
☕️ Languages I Know: 
* Html
* css
* javascript
* english.
I could translate stuff for you. Or, I could build you a website with free hosting. 😀 ; Just let me know.

**Comment by b3u** [comment]
Thank you for the list. I'd love to help with the game itself, but I'm not a modeler or a Unity Programmer. Are you interested at all in a website? It would be hosted free by Github pages, so you would probably create a repo, and I'd fork it and then put in a pull request.

**Comment by OpenHogwarts** [comment]
Can't it be made on the same repo? Or what would happen?

**Comment by b3u** [comment]
If you set up a repository named `<username>.github.io`, the site would be the repo name. If you do it in a different repo, it would called, for example, `OpenHogwarts.github.io/OpenHogwarts`.

**Comment by OpenHogwarts** [comment]
I think it's ready now: "Your site is ready to be published at http://openhogwarts.github.io/hogwarts/." It's the `/docs/` folder :)

**Comment by b3u** [comment]
Update:
* Desktop view is finished.
* Mobile view is not, but shouldn't take that long.
* Still want to implement a slideshow background on the first page.
* *I'll make it live with GitHub pages so you can see it before I open a pull request*

**Comment by OpenHogwarts** [comment]
Just github :)

**Comment by b3u** [comment]
Check it out: https://b3u.github.io/hogwarts/. What do you think?
