### ISSUE TITLE
Add proper license for project

### ISSUE THREAD

**Issue by KonH** [OpenHogwarts/hogwarts#60]
Can you please add license file into repository? For now, any contribution is "illegal" (look into for e.g. https://opensource.stackexchange.com/a/1721), because of lack of license information. If you don't want to think about license limitations and allow anyone to contribute without restrictions, you can just use MIT, its template already proposed by GitHub, if you trying to add LICENSE file into root directory via we interface.

**Comment by OpenHogwarts** [comment]
If you can recommend a license that doesn't grant any right to sell/resell, only to modify & redistribute for free and also says copyright ownership is from their respective authors, not ours. I will add it.

**Comment by KonH** [comment]
I'm not a lawyer, but you can take a look at this one - https://creativecommons.org/licenses/by-nc/3.0/us/.

**Comment by OpenHogwarts** [comment]
Fixed in https://github.com/OpenHogwarts/hogwarts/commit/bd9a08c3100c666b9916bf64160d28146ef677f1 !
