### ISSUE TITLE
What version of Unity is recommended for this project?

### ISSUE THREAD

**Issue by BridgetNichols** [OpenHogwarts/hogwarts#61]
I'd really like to help work on this project, but their are so many compiler errors that I just can't even test the game out as I keep having to fix bug after bug. I'm thinking it may have something to do with my current version of Unity(2018.3.5f1), because all of the bugs I'm encountering are typically somewhat related to the version of Unity I'm using. 

I saw in the readme that it should work in versions 2017.4.0f1 and up, but it doesn't seem to be working on my version. Does anybody have this game working, and if so what version of the engine are you using?

**Comment by OpenHogwarts** [comment]
Hi @BridgetNichols , `ProjectVersion.txt` is a Unity file, which shows the version that was last used so that's the version that compiled it properly.

Could you show the errors? Did you try to close and reopen the project after importing it?

**Comment by BridgetNichols** [comment]
@OpenHogwarts Thank you for getting back to me so soon. I was kind of worried because their hasn't been a lot of activity in a while for this project, but now I feel a lot better. I'm currently downloading the version from `ProjectVersion.txt` and I'll see if that works otherwise I'll post all of the errors I'm getting.

**Comment by BridgetNichols** [comment]
Alright it's now working, thank you so much! I just downloaded 2017.4.29f and it worked like a charm. Their are probably some later versions that work, but this version works just fine, and it saves me a lot of hassle. Time to get working!

**Comment by OpenHogwarts** [comment]
I will update the readme to let it know that newer versions may require fixes :)
