### ISSUE TITLE
Not able to build in the unity 2019

### ISSUE THREAD

**Issue by sakshams21** [OpenHogwarts/hogwarts#67]
I tried to open this project in the latest version of the unity, but it wont build properly if push to open in the latest version what to do if i want to open this project in the latest unity 2019 version

**Comment by OpenHogwarts** [comment]
`but it wont build properly`
Please be more specific, no one can help you if you only say "it doesnt work".

**Comment by finchen** [comment]
@OpenHogwarts would you like to upgrade? or do you know if it won't be possible? I can try one day

**Comment by OpenHogwarts** [comment]
Upgraded!
