### ISSUE TITLE
Continuation of the project

### ISSUE THREAD

**Issue by ivan311** [OpenHogwarts/hogwarts#74]
Is there any possibility for the project to be updated? even using the indicated version it still has an error in the codes. could you update please?

I hope this project doesn't die

**Comment by tetreum** [comment]
Please, don't confuse warnings with errors, the game even works with unity's latest version.

**Comment by tetreum** [comment]
Project got upgraded to Unity 2020.3.30f1 .
Unity's preview packages got removed. Maybe that fixes your issues.
