### ISSUE TITLE
Need a developer?

### ISSUE THREAD

**Issue by scentedwax** [OpenHogwarts/hogwarts#85]
Hello👋

What if I try to:
* Fix mouse, aiming and interactions with env, camera, movements
* change a bit broomstick flyings (add more realistic movements, animations, speed)
* Fix characters name labels
* Add more terrain (nature, trees, mountains, etc) far from castle

All I'll do is just up to my enthusiasm. I'll try to do best.

**Comment by OpenHogwarts** [comment]
That's the beauty of open source projects :) . You can fork it and start making any improvement you want and then send it as PR !

**Comment by scentedwax** [comment]
Thanks
