### ISSUE TITLE
Is the work still going on?

### ISSUE THREAD

**Issue by ManasDeyvloper** [OpenHogwarts/hogwarts#87]
Ive been a game developer for past 2 years and well versed with Unity3D and C# programming. I was wondering if any help is needed?

**Comment by Phq-art** [comment]
well looks like we found this too late :/

**Comment by OpenHogwarts** [comment]
Well it's been quite a while, te best way to help is just to play it for a bit to see what's missing an attack it ;)

**Comment by ManasDeyvloper** [comment]
Awesome, ive been developing softwares for quite some time now and wanting to get into proper 'game' dev field for a while, this might be my ticket in
