### ISSUE TITLE
Gameplay video?

### ISSUE THREAD

**Issue by FoxxMD** [OpenHogwarts/hogwarts#9]
The list of working features is impressive! For someone thinking about trying this out but not sure if it's worth the time investment in getting the dev environment setup it would extremely helpful to see some videos of gameplay.

Would you consider putting some demos of gameplay on youtube or something?

**Comment by OpenHogwarts** [comment]
Missed to show some features and Seller panel is fucked up but, it's a WIP project, u know:
https://www.youtube.com/watch?v=Kra8mhuHzx4
